---
  - hosts: all
    remote_user: vagrant
    become: true
    gather_facts: no
    check_mode: no
    ignore_errors: true
    tasks:
        - name: Install apache
          apt:
            name: apache2
            state: present
          notify: restart apache
    handlers: 
        - name: restart apache
          service: 
            name: apache2
            state: started